# Generated by Django 3.0.7 on 2020-06-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Название события')),
                ('content', models.TextField(blank=True, verbose_name='Содержание проекта')),
                ('eventDate', models.DateTimeField(verbose_name='Дата события')),
                ('done', models.BooleanField(blank=True, default=False, verbose_name='Выполнено')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания проекта')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'Собыитя',
            },
        ),
    ]
